# Generated by Django 6.0.2 on 2026-02-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-score']},
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='balance',
            new_name='score',
        ),
    ]
